### Exercise 1

Write a loop that enables to calculate the sum of the 23 first integers.

In [ ]:
s = 0
for i in range(24):
    s = s + i
print(s)

### Exercise 2

calculates the factorial of 12 using a while loop.

In [ ]:
f = 1
a = 1
while a < 12:
    a = a + 1
    f = f * a
print(f)

### Exercise 3
Write and test the previous code with different values of a.

In [ ]:
a=4
if a==0:
    print("0")
elif a==1:
    print("1")
else:
    print("2")

### Exercise 4

Write a program that asks the user to enter student marks. If the user enters a negative value, the
program stops. On the other hand, for each mark entered, the program progressively builds a list.
After each entry of a new mark (and therefore every iteration of the loop), it displays the number
of marks entered, the highest mark, the lowest mark, the average of all the marks.

Tip: To create an empty list, it is sufficient to set the command line = [].

In [2]:
from statistics import mean
line = []
note =0
while(note >= 0):
    note = int(input("insert a new note \n"))
    line.append(note)
    print(line)
    print("Nb marks : ",len(line))
    print("Max : ",max(line))
    print("Min : ",min(line))
# print("Avg : ",np.mean(line))
    print("Avg : ",mean(line))

[10]
Nb marks :  1
Max :  10
Min :  10
Avg :  10
[10, 5]
Nb marks :  2
Max :  10
Min :  5
Avg :  7.5
[10, 5, 8]
Nb marks :  3
Max :  10
Min :  5
Avg :  7.666666666666667
[10, 5, 8, 7]
Nb marks :  4
Max :  10
Min :  5
Avg :  7.5
[10, 5, 8, 7, 12]
Nb marks :  5
Max :  12
Min :  5
Avg :  8.4
[10, 5, 8, 7, 12, 0]
Nb marks :  6
Max :  12
Min :  0
Avg :  7


ValueError: invalid literal for int() with base 10: ''

### Exercise 5 

Write a script that enables to obtain the following result (:

Write a sentence
une chaine

The inversed sentence is:
eniahc enu

In [1]:
s = input("Write a sentence ")
print(s)
print()
print("The inversed sentence is:")
print(s[::-1])

Write a sentence -1
-1

The inversed sentence is:
1-


### Exercise 6 
Define a function that enables to calculate the volume of a sphere (the radius is a parameter of the function).

In [3]:
from math import *
def volumeSphere(radius):
    return ((4*pi / 3) * radius**3)

In [4]:
volumeSphere(2)

33.510321638291124

### Exercise 7
Write a function that computes the sum of the integers passed in parameters.

In [5]:
def my_sum(*args):
    return sum(args)

In [6]:
my_sum(1,2,5)

8

# Numpy Correction

## Exercise 1

In [12]:
import numpy as np

t1 = np.random.uniform(-1.0, 1.0, 100)

# Calculate mean of t1
mean_t1 = np.mean(t1)

# Calculate median of t1
median_t1 = np.median(t1)

# Calculate standard deviation of t1
std_t1 = np.std(t1)

# Print the results
print("Mean of t1:", mean_t1)
print("Median of t1:", median_t1)
print("Standard Deviation of t1:", std_t1)

# Create t2 with positive values from t1
t2 = t1[t1 > 0]

# Create t3 with negative values from t1
t3 = t1[t1 < 0]

# Create t4 by removing negative values from t1
t4 = t1[t1 >= 0]

# Create t5 by replacing values in t1 greater than 0.5 with 1.0
t5 = np.where(t1 > 0.5, 1.0, t1)

# Find the maximum value in t1
max_t1 = np.max(t1)

# Find the minimum value in t1
min_t1 = np.min(t1)

# Reshape t1 into a 25x4 matrix m1
m1 = t1.reshape(25, 4)

# Print the first few rows of m1 to verify
print("First few rows of m1 (25x4 matrix):")
print(m1[:5])  # Displaying the first 5 rows for a quick look

mean_rows = np.mean(m1, axis=1)

# Compute mean values for each column of m1
mean_columns = np.mean(m1, axis=0)

# Print the results
print("Mean values for the first few rows of m1:", mean_rows[:5])
print("Mean values for each column of m1:", mean_columns)

# Create a copy of m1 to modify, resulting in m2
m2 = np.copy(m1)  

# 9. Replace randomly chosen values in each column with np.nan
np.random.seed(0)  # For reproducibility of results
for col in range(m2.shape[1]):
    random_row = np.random.randint(0, m2.shape[0])
    m2[random_row, col] = np.nan

# Print the first few rows of m2 to verify
print("First few rows of m2:")
print(m2[:5])

# 10. Count NaN values in m2
nan_count = np.isnan(m2).sum()

# Find indexes of NaNs in m2
nan_indexes = np.argwhere(np.isnan(m2))

# Print the count and the first few indexes of NaNs
print("Number of NaN values in m2:", nan_count)
print("Indexes of first few NaN values in m2:", nan_indexes[:5])

# 11. Compute mean of the 1st column of m2, excluding NaNs
mean_col1_without_nan = np.nanmean(m2[:, 0])

# Replace NaNs in the 1st column of m2 with the mean value
m2[np.isnan(m2[:, 0]), 0] = mean_col1_without_nan

# Print the mean value and the first few rows of m2 for verification
print("Mean of the 1st column without NaNs:", mean_col1_without_nan)
print("First few rows of m2 after replacing NaNs in the 1st column:")
print(m2[:5])

#12 & 13
def removeNaNs(mat, c):
    """
    Replace NaNs in a specified column of a matrix with the mean value of that column.

    Parameters:
    mat (numpy.ndarray): The matrix in which NaNs are to be replaced.
    c (int): The column index where NaNs should be replaced.

    Returns:
    numpy.ndarray: The modified matrix with NaNs replaced in the specified column.
    """
    mean_col = np.nanmean(mat[:, c])  # Compute mean of the column, excluding NaNs
    mat[np.isnan(mat[:, c]), c] = mean_col  # Replace NaNs in the column with the mean value
    return mat

# Example usage of the function
# Assuming m2 is a matrix with NaN values
# Let's apply the function to the second column (index 1) of m2 as an example
m2_modified = removeNaNs(m2, 1)

print("First few rows of m2 after applying removeNaNs to the second column:")
print(m2_modified[:5])

# 14. Find the max value for each column of m1
max_values_columns = np.max(m1, axis=0)

# Print the max values for each column
print("Max values for each column of m1:", max_values_columns)

# 15. Find the min value for each row of m1
min_values_rows = np.min(m1, axis=1)

# Print the min values for each row
print("Min values for each row of m1:", min_values_rows)

Mean of t1: -0.06073588818119166
Median of t1: -0.07220986489076187
Standard Deviation of t1: 0.5772141263359828
First few rows of m1 (25x4 matrix):
[[ 0.20552675  0.08976637 -0.1526904   0.29178823]
 [-0.12482558  0.783546    0.92732552 -0.23311696]
 [ 0.58345008  0.05778984  0.13608912  0.85119328]
 [-0.85792788 -0.8257414  -0.95956321  0.66523969]
 [ 0.5563135   0.7400243   0.95723668  0.59831713]]
Mean values for the first few rows of m1: [ 0.10859774  0.33823225  0.40713058 -0.4944982   0.7129729 ]
Mean values for each column of m1: [-0.02559285 -0.17930966  0.03643809 -0.07447914]
First few rows of m2:
[[ 0.20552675  0.08976637 -0.1526904          nan]
 [-0.12482558  0.783546    0.92732552 -0.23311696]
 [ 0.58345008  0.05778984  0.13608912  0.85119328]
 [-0.85792788 -0.8257414  -0.95956321  0.66523969]
 [ 0.5563135   0.7400243   0.95723668  0.59831713]]
Number of NaN values in m2: 4
Indexes of first few NaN values in m2: [[ 0  3]
 [12  0]
 [15  1]
 [21  2]]
Mean of the 1st column

## Exercise 2

In [14]:
import numpy as np

# Set a random seed for reproducibility (optional)
np.random.seed(42)

print(m)

def count_unique_values_row_wise(arr):
    # Ensure that the input array contains integers in the range [0, 10]
    if not (0 <= arr.min() and arr.max() <= 10):
        raise ValueError("Input array should contain values in the range [0, 10]")
    
    # Initialize an empty result matrix with zeros
    result = np.zeros((arr.shape[0], 11), dtype=int)
    
    # Iterate through each row and compute the bincount
    for i, row in enumerate(arr):
        counts = np.bincount(row, minlength=11)
        result[i] = counts
    
    return result

# Create a 10x6 array with random integers in [0, 10]
m = np.random.randint(0, 11, size=(10, 6))

# Compute the counts of unique values row-wise
counts_matrix = count_unique_values_row_wise(m)

print(counts_matrix)

[[ 3  1  5  5  9  3]
 [ 5  1  9  1  9  3]
 [ 7  6  8  7  4  1]
 [ 4  7  9  8  8  0]
 [ 8  6  8  7  0  7]
 [ 7 10  2  0  7  2]
 [ 2  0 10  4  9  6]
 [ 9  8  6  8  7  1]
 [ 0  6  6  7  4  2]
 [ 7  5 10  2  0  2]]
[[0 0 0 1 1 0 2 1 0 0 1]
 [0 0 1 0 0 0 1 1 0 1 2]
 [0 0 1 1 1 1 0 2 0 0 0]
 [0 2 0 0 2 1 0 1 0 0 0]
 [2 0 0 0 0 1 0 0 1 1 1]
 [0 0 1 1 0 0 1 0 1 1 1]
 [0 0 2 0 2 0 1 0 1 0 0]
 [0 2 0 1 0 0 1 0 1 1 0]
 [0 1 0 1 1 0 1 0 1 1 0]
 [1 1 1 1 0 0 0 2 0 0 0]]
